server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/elberthbrandao/ead-config-server-repo
          default-label: main
          username: ${EAD-CONFIG-SERVER-GITHUB-USERNAME}
          password: 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

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost